# Generated by Django 6.0 on 2025-12-15 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_categories', to='treasurer.meeting')),
            ],
            options={
                'verbose_name_plural': 'Reading categories',
                'ordering': ['order', 'name'],
                'unique_together': {('meeting', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ReadingsModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_enabled', models.BooleanField(default=True, help_text='Allow public viewing of readings')),
                ('share_token', models.CharField(blank=True, help_text='Token for public share link', max_length=64, unique=True)),
                ('show_sources', models.BooleanField(default=True, help_text='Show source citations on public pages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readings_config', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Readings Configuration',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, help_text='e.g., "Big Book p. 58-60"', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown publicly)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='treasurer.meeting')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='readings.readingcategory')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('meeting', 'slug')},
            },
        ),
    ]
