# Generated by Django 6.0 on 2025-12-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsmoduleconfig',
            name='display_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', help_text='Font size on public pages', max_length=20),
        ),
        migrations.AddField(
            model_name='readingsmoduleconfig',
            name='editor_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', help_text='Font size in the content editor', max_length=20),
        ),
    ]
