# Generated by Django 6.0 on 2025-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_readingsmoduleconfig_display_font_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='source',
        ),
        migrations.AddField(
            model_name='reading',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for use in meeting format links (e.g., "12 Traditions")', max_length=50),
        ),
    ]
