# Generated by Django 6.0 on 2025-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_add_short_name_remove_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this reading'),
        ),
    ]
