# Generated by Django 6.0 on 2025-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_add_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='copyright_notice',
            field=models.TextField(blank=True, help_text='Copyright notice shown at bottom of reading (e.g., source attribution)'),
        ),
    ]
