# Generated by Django 6.0 on 2025-12-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='sobriety_term',
            field=models.CharField(choices=[('sobriety', 'Sobriety (AA)'), ('abstinence', 'Abstinence (OA)'), ('clean', 'Clean Time (NA)'), ('recovery', 'Recovery')], default='sobriety', help_text='Term used for sobriety/abstinence dates', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
