# Generated by Django 6.0 on 2025-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_sobriety_term_and_pdf_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='sobriety_term_other',
            field=models.CharField(blank=True, help_text='Custom term if "Other" is selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingconfig',
            name='sobriety_term',
            field=models.CharField(choices=[('sobriety', 'Sobriety'), ('abstinence', 'Abstinence'), ('clean', 'Clean Time'), ('recovery', 'Recovery'), ('other', 'Other')], default='sobriety', max_length=20),
        ),
    ]
