# Generated by Django 6.0 on 2025-12-20 03:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_sobriety_term_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceposition',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can this position add/edit/remove users?'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='duties',
            field=models.TextField(blank=True, help_text='Position duties and responsibilities'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Module access: {"treasurer": "write", "phone_list": "read"}'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='show_on_public_site',
            field=models.BooleanField(default=False, help_text='Show this position in the public officers directory'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='sobriety_requirement',
            field=models.CharField(blank=True, help_text='e.g., "1 year continuous"', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='sop',
            field=models.TextField(blank=True, help_text='Standard Operating Procedures'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='term_months',
            field=models.PositiveIntegerField(default=6, help_text='Default term length in months'),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceposition',
            name='warn_on_multiple_holders',
            field=models.BooleanField(default=True, help_text='Show warning when multiple people hold this position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text='[DEPRECATED] Use PositionAssignment instead', related_name='users', to='core.serviceposition'),
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for current holders', null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g., "Appointed mid-term to replace previous holder"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.serviceposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position Assignment',
                'verbose_name_plural': 'Position Assignments',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
