# Generated by Django 6.0 on 2025-12-20 03:17

from datetime import date
from django.db import migrations


def migrate_m2m_to_assignments(apps, schema_editor):
    """
    Migrate User.positions M2M data to PositionAssignment records.
    Also set up default module_permissions and can_manage_users for existing positions.
    """
    User = apps.get_model('core', 'User')
    ServicePosition = apps.get_model('core', 'ServicePosition')
    PositionAssignment = apps.get_model('core', 'PositionAssignment')

    # Default permission configurations for built-in positions
    default_configs = {
        'treasurer': {
            'can_manage_users': True,
            'module_permissions': {
                'treasurer': 'write',
                'phone_list': 'read',
            },
            'term_months': 6,
        },
        'secretary': {
            'can_manage_users': True,
            'module_permissions': {
                'meeting_format': 'write',
                'readings': 'write',
                'phone_list': 'write',
                'website': 'write',
            },
            'term_months': 6,
        },
        'literature': {
            'can_manage_users': False,
            'module_permissions': {},
            'term_months': 6,
        },
        'gsr': {
            'can_manage_users': False,
            'module_permissions': {},
            'term_months': 12,
        },
        'group_rep': {
            'can_manage_users': False,
            'module_permissions': {},
            'term_months': 12,
        },
    }

    # Update existing positions with default configs
    for position in ServicePosition.objects.all():
        config = default_configs.get(position.name, {})
        if config:
            position.can_manage_users = config.get('can_manage_users', False)
            position.module_permissions = config.get('module_permissions', {})
            position.term_months = config.get('term_months', 6)
            position.save()

    # Migrate M2M relationships to PositionAssignment
    for user in User.objects.prefetch_related('positions').all():
        for position in user.positions.all():
            # Check if assignment already exists
            if not PositionAssignment.objects.filter(
                user=user,
                position=position,
                end_date__isnull=True
            ).exists():
                PositionAssignment.objects.create(
                    user=user,
                    position=position,
                    start_date=user.created_at.date() if user.created_at else date.today(),
                    end_date=None,  # Current holder
                    notes='Migrated from legacy M2M relationship'
                )


def reverse_migration(apps, schema_editor):
    """
    Reverse: Delete migrated PositionAssignment records and restore M2M.
    Note: This only restores current assignments, not historical ones.
    """
    User = apps.get_model('core', 'User')
    PositionAssignment = apps.get_model('core', 'PositionAssignment')

    # For each current assignment, ensure M2M exists
    for assignment in PositionAssignment.objects.filter(end_date__isnull=True):
        assignment.user.positions.add(assignment.position)

    # Delete assignments that were migrated
    PositionAssignment.objects.filter(
        notes='Migrated from legacy M2M relationship'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_position_management'),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_assignments, reverse_migration),
    ]
