# Generated by Django 6.0 on 2025-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_positions_to_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionassignment',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary position = filled. Secondary = position still needs someone.'),
        ),
    ]
