# Generated by Django 6.0 on 2025-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_position_assignment_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceposition',
            options={'ordering': ['display_name']},
        ),
        migrations.AddField(
            model_name='meetingconfig',
            name='public_officers_display',
            field=models.CharField(choices=[('hidden', 'Not visible'), ('positions_only', 'Positions and vacancy status only'), ('names', 'Positions, vacancy, and officer first name + last initial')], default='positions_only', help_text='How to display service positions on the public site', max_length=20),
        ),
    ]
