# Generated by Django 6.0 on 2026-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_create_group_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a favicon image (recommended: 32x32 or 64x64 PNG/ICO)', null=True, upload_to='favicon/'),
        ),
    ]
