# Generated by Django 6.0 on 2026-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='setup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='pending', help_text='Setup wizard status', max_length=20),
        ),
    ]
