# Generated by Django 6.0 on 2026-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_setup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for the website header (recommended: max 200px height)', null=True, upload_to='logo/'),
        ),
    ]
