# Generated by Django 6.0 on 2026-01-24 03:17

from django.db import migrations, models


def mark_group_member_as_membership(apps, schema_editor):
    ServicePosition = apps.get_model('core', 'ServicePosition')
    ServicePosition.objects.filter(name='group_member').update(is_membership_position=True)


def unmark_group_member(apps, schema_editor):
    ServicePosition = apps.get_model('core', 'ServicePosition')
    ServicePosition.objects.filter(name='group_member').update(is_membership_position=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_default_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceposition',
            name='is_membership_position',
            field=models.BooleanField(default=False, help_text='Membership positions are auto-assigned and hidden from service positions list'),
        ),
        migrations.RunPython(mark_group_member_as_membership, unmark_group_member),
    ]
