# Generated by Django 6.0 on 2026-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_is_membership_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Required for login. Leave blank for placeholder users.', max_length=254, null=True, unique=True),
        ),
    ]
