# Generated by Django 6.0 on 2025-12-15 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Block title, e.g., "Welcome", "Main Content", "Closing"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_blocks', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Format Block',
                'verbose_name_plural': 'Format Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlockVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variation name, e.g., "Speaker", "Topic", "Literature"', max_length=50)),
                ('content', models.TextField(blank=True, help_text='Rich HTML content. Use [reading_slug] to link to readings.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='Use this variation when no schedule matches')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='meeting_format.formatblock')),
            ],
            options={
                'verbose_name': 'Block Variation',
                'verbose_name_plural': 'Block Variations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormatModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_enabled', models.BooleanField(default=True, help_text='Allow public access to meeting format')),
                ('share_token', models.CharField(blank=True, help_text='Token for public URL', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='format_config', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Format Configuration',
                'verbose_name_plural': 'Format Configurations',
            },
        ),
        migrations.CreateModel(
            name='VariationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('weekday_occurrence', '1st/2nd/3rd/4th/5th weekday of month'), ('day_of_week', 'Every weekday'), ('specific_date', 'Specific date')], max_length=20)),
                ('occurrence', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], help_text='Which occurrence (1st, 2nd, etc.)', null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='Specific date for this variation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meeting_format.blockvariation')),
            ],
            options={
                'verbose_name': 'Variation Schedule',
                'verbose_name_plural': 'Variation Schedules',
            },
        ),
    ]
