# Generated by Django 6.0 on 2025-12-15 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_format', '0002_formatmoduleconfig_display_font_size_and_more'),
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockvariation',
            name='name',
        ),
        migrations.AlterField(
            model_name='blockvariation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this variation when no meeting type is selected'),
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Meeting type name, e.g., "Speaker", "Topic", "Literature"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_types', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Type',
                'verbose_name_plural': 'Meeting Types',
                'ordering': ['order', 'name'],
                'unique_together': {('meeting', 'name')},
            },
        ),
        migrations.AddField(
            model_name='blockvariation',
            name='meeting_type',
            field=models.ForeignKey(blank=True, help_text='Meeting type this variation belongs to (e.g., Speaker, Topic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='meeting_format.meetingtype'),
        ),
        migrations.AddField(
            model_name='formatmoduleconfig',
            name='selected_meeting_type',
            field=models.ForeignKey(blank=True, help_text='Currently selected meeting type for public display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meeting_format.meetingtype'),
        ),
    ]
