# Generated by Django 6.0 on 2025-12-22 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMeetingFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='<h2>Opening</h2>\n<p>[Opening prayer or moment of silence]</p>\n\n<h2>Review Previous Minutes</h2>\n<p>[Secretary reads or summarizes previous meeting minutes]</p>\n\n<h2>Officer Reports</h2>\n<ul>\n<li>Treasurer Report</li>\n<li>Secretary Report</li>\n<li>GSR Report</li>\n<li>[Other positions as applicable]</li>\n</ul>\n\n<h2>Old Business</h2>\n<p>[Unfinished items from previous meetings]</p>\n\n<h2>New Business</h2>\n<p>[New items for discussion]</p>\n\n<h2>Closing</h2>\n<p>[Closing prayer]</p>', help_text='The format/script for running business meetings.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_meeting_format', to='treasurer.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Meeting Format',
                'verbose_name_plural': 'Business Meeting Formats',
            },
        ),
        migrations.CreateModel(
            name='BusinessMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Meeting notes/minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_meetings_created', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_meetings', to='treasurer.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_meetings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Meeting',
                'verbose_name_plural': 'Business Meetings',
                'ordering': ['-date'],
                'unique_together': {('meeting', 'date')},
            },
        ),
    ]
