# Generated by Django 6.0 on 2025-12-06 03:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name, e.g., 'Standard Split'", max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disbursement Split',
                'verbose_name_plural': 'Disbursement Splits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementSplitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'District', 'Area', 'World Service'", max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('order', models.PositiveIntegerField(default=0)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treasurer.disbursementsplit')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_disbursement', models.BooleanField(default=False, help_text='Whether this is a disbursement category (triggers split calculation)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
                'unique_together': {('meeting', 'name')},
            },
        ),
        migrations.AddField(
            model_name='disbursementsplit',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_splits', to='treasurer.meeting'),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.expensecategory')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='treasurer.meeting')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='TreasurerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prudent_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to keep in reserve for group security', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial balance when tracking began', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_settings', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Treasurer Settings',
                'verbose_name_plural': 'Treasurer Settings',
            },
        ),
        migrations.CreateModel(
            name='TreasurerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('split_name', models.CharField(blank=True, help_text="Name of the split (e.g., 'District') if part of a disbursement", max_length=255)),
                ('receipt_image', models.ImageField(blank=True, help_text='Photo of receipt for this transaction', null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='treasurer.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_records', to='treasurer.meeting')),
                ('parent_record', models.ForeignKey(blank=True, help_text='Parent record if this is a split disbursement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_records', to='treasurer.treasurerrecord')),
                ('recurring_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_records', to='treasurer.recurringexpense')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['meeting', 'date'], name='treasurer_t_meeting_0b7036_idx'), models.Index(fields=['meeting', 'type'], name='treasurer_t_meeting_1189f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreasurerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='Date the report was generated')),
                ('start_date', models.DateField(help_text='First day of the report period')),
                ('end_date', models.DateField(help_text='Last day of the report period')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prudent_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived reports are locked and not used for next period calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_reports', to='treasurer.meeting')),
            ],
            options={
                'ordering': ['-report_date', '-end_date'],
                'indexes': [models.Index(fields=['meeting', 'is_archived'], name='treasurer_t_meeting_143bfe_idx'), models.Index(fields=['meeting', 'start_date', 'end_date'], name='treasurer_t_meeting_a2e7c9_idx')],
            },
        ),
    ]
