# Generated by Django 6.0 on 2025-12-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasurerrecord',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='treasurerrecord',
            name='receipt',
            field=models.FileField(blank=True, help_text='Receipt image (JPG, PNG) or PDF', null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
