# Generated by Django 6.0 on 2025-12-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_receipt_field_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurerrecord',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for expense transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='treasurer.expensecategory'),
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Default category for new income (typically 7th Tradition)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Income Category',
                'verbose_name_plural': 'Income Categories',
                'ordering': ['name'],
                'unique_together': {('meeting', 'name')},
            },
        ),
        migrations.AddField(
            model_name='treasurerrecord',
            name='income_category',
            field=models.ForeignKey(blank=True, help_text='Category for income transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='treasurer.incomecategory'),
        ),
    ]
