# Generated by Django 6.0 on 2025-12-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_list', '0002_seed_timezones'),
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_zones', to='treasurer.meeting'),
        ),
    ]
