# Generated by Django 6.0 on 2025-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_list', '0003_add_meeting_to_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time_zone_other',
            field=models.CharField(blank=True, help_text='Custom time zone if not in list', max_length=50),
        ),
    ]
