# Generated by Django 6.0 on 2025-12-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_list', '0004_add_timezone_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_font_size',
            field=models.PositiveSmallIntegerField(choices=[(8, '8pt (Very Compact)'), (9, '9pt (Compact)'), (10, '10pt (Standard)'), (11, '11pt (Large)'), (12, '12pt (Extra Large)')], default=9, help_text='Font size for PDF export'),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_footer_text',
            field=models.CharField(blank=True, default="This phone list is for meeting members only. Please respect everyone's privacy.", help_text='Footer text on PDF (leave blank for none)', max_length=500),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_layout',
            field=models.CharField(choices=[('table', 'Table'), ('two_column', 'Two-Column List')], default='table', help_text='Layout style for PDF export', max_length=20),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_show_email',
            field=models.BooleanField(default=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_show_phone',
            field=models.BooleanField(default=True, verbose_name='Phone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_show_sobriety',
            field=models.BooleanField(default=False, verbose_name='Sobriety Date'),
        ),
        migrations.AddField(
            model_name='phonelistconfig',
            name='pdf_show_time_zone',
            field=models.BooleanField(default=True, verbose_name='Time Zone'),
        ),
    ]
