# Generated by Django 6.0 on 2025-12-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasurer', '0003_alter_treasurerrecord_category_incomecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('content', models.TextField(blank=True, help_text='HTML content from WYSIWYG editor')),
                ('is_published', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Show in public navigation menu')),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_pages', to='treasurer.meeting')),
            ],
            options={
                'verbose_name': 'Website Page',
                'verbose_name_plural': 'Website Pages',
                'ordering': ['nav_order', 'title'],
                'unique_together': {('meeting', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_type', models.CharField(choices=[('format', 'Meeting Format'), ('page', 'CMS Page')], default='format', max_length=10)),
                ('public_format_enabled', models.BooleanField(default=True, help_text='Show Meeting Format in public navigation')),
                ('public_readings_enabled', models.BooleanField(default=True, help_text='Show Readings in public navigation')),
                ('public_phone_list_enabled', models.BooleanField(default=False, help_text='Show Phone List in public navigation')),
                ('show_login_link', models.BooleanField(default=True, help_text='Show login link in public navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_config', to='treasurer.meeting')),
                ('home_cms_page', models.ForeignKey(blank=True, help_text='CMS page to show as home (when home_page_type=page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.websitepage')),
            ],
            options={
                'verbose_name': 'Website Configuration',
                'verbose_name_plural': 'Website Configurations',
            },
        ),
    ]
