# Generated by Django 6.0 on 2025-12-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemoduleconfig',
            name='public_treasurer_enabled',
            field=models.BooleanField(default=False, help_text='Show Treasurer Reports in public navigation'),
        ),
    ]
