# Generated by Django 6.0 on 2025-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_public_treasurer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='rendered_html',
            field=models.TextField(blank=True, help_text='Cached HTML render of Puck content'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Puck editor JSON content'),
        ),
    ]
