# Generated by Django 6.0 on 2025-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_puck_json_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Featured image URL for social sharing'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description for search engines', max_length=160),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (defaults to page title if blank)', max_length=70),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
