# Generated by Django 6.0 on 2025-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepage',
            name='featured_image',
            field=models.CharField(blank=True, help_text='Featured image path', max_length=500),
        ),
    ]
